---
title: "COVID-19 Vaccination in Nigeria"
description: |
 This post contains simple overview of the COVID-19 statistics in Nigeria and the vaccination statistics up till August, 2021.
author:
  - name: Tina Tsou
date: 09-01-2021
categories:
  - Covid-19
  - Nigeria
  - Vaccination
output:
  distill::distill_article:
    self_contained: false
    toc: true
bibliography: ../../references.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)

```
## Introduction
As we move towards the third quarter of 2021, many countries around the world have been accelerating their vaccination process. In this blog post, I will be giving an simple overview of the situation in Nigeria.


## Data Description
```{r libraries}
# load library
library(tidyverse)
library(broom)
library(ggplot2)
library(DT)
library(plotly)
```

```{r data}
nigeria <- read.csv(here::here("data","WHO_Nigeria.csv"))
source<- read.csv(here::here("data","COVID-19 Vaccine Doses in HRP Countries - Deliveries.csv"))
vaccination <-readr::read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv")
```

```{r vaccination related}
vaccine_source <- source %>% 
  filter(f == "Nigeria")
 
vaccination_cleaned <- vaccination%>%
  filter(location == "Nigeria")
```






